### PR TITLE
waste-audit

### PR DESCRIPTION
**Pull request by kandrewz**
article on recent 2019 waste audits

### CODE REVIEW

**Comment by hennadialani** [comment]
@kandrewz change the ruby version of your branch! the deploy preview is dying rn :'(

**Comment by hennadialani** [comment]
such! a! big! fan! just going to add a few further comments because i know you're still hashing this out but just things to keep in mind/fix along the way:

"constantly reminded of the Zero Food Waste by 2020 initiative" <- see if you think it's appropriate for a photo of a sign/whatever to be there and lmk so that i can ask for someone from the photo section to take a photo sooner than later.

By student rooms do you mean dorms?

At Powell, they've recently added snazzier graphics showing what's recyclable or not. 

for the game/interactive, do you wanna backpopulate it first with responses by real people (aka DB staffers for example)

let's try to keep fonts consistent to the extent possible.

consider using the screenshot of your game (maybe just the bins?) instead of the graphs?

that's all from me for now!! this is fantastic work.

**Comment by mattiesansev** [comment]
the image is a little confusing, when i first opened it I wasn't sure if the game was starting at the top or if it was just an image. Is there any way you can change the image or make it look more distinct as an image rather than the game itself?

**Comment by mattiesansev** [comment]
can you add an extra empty line between the text and the game? or make a box around the game? the jump to the game feels a little abrupt

**Pull request merged**
